global:
  enabled: true
  tlsDisable: true
injector:
  enabled: true
ui:
  enabled: true
server:
  ha:
    enabled: true
    replicas: 1
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "consul" {
        address = "consul-server.consul.svc.cluster.local:8500"
        path    = "vault/"
      }
      service_registration "kubernetes" {}

